language: java
jdk:
  - oraclejdk8

addons:
  apt:
    sources:
    - heroku
    packages:
    - heroku-toolbelt script:
  - ./gradlew clean
  - ./gradlew check
  - git remote add heroku git@heroku.com:TicTacToe.git
  # Add your Heroku API key:
  - export HEROKU_API_KEY=78a31987-148d-45b8-b804-55feef602960
  # Turn off warnings about SSH keys:
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo " StrictHostKeyChecking no" >> ~/.ssh/config
  - echo " CheckHostIP no" >> ~/.ssh/config
  - echo " UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  # Clear your current Heroku SSH keys:
  - heroku keys:clear
  # Add a new SSH key to Heroku
  - yes | heroku keys:add
  # Push to Heroku!
  - yes | git push heroku master
  - sleep 15
